apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secrets-sync
  namespace: development
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: argocd-secret
  refreshAfter: 1m
  destination:
    name: argocd-secret
    create: true
    type: Opaque
    transformation:
      templates:
        admin-password:
          text: '{{ get .Secrets "admin.password" }}'
        server-secretkey:
          text: '{{ get .Secrets "server.secretkey" }}'