apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: portainer-secrets-sync
  namespace: monitoring
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: portainer-admin-password
  refreshAfter: 1m
  destination:
    name: portainer-admin-password
    create: true
    type: Opaque
    transformation:
      templates:
        password:
          text: '{{ get .Secrets "password" }}'