apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: vault-auth-global
  namespace: secrets
spec:
  defaultAuthMethod: kubernetes
  defaultMount: kubernetes
  allowedNamespaces:
    - "*"
