apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: romm-credentials-sync
  namespace: gaming
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: romm-credentials
  refreshAfter: 1m
  destination:
    name: romm-credentials
    create: true
    overwrite: true
    type: Opaque
    transformation:
      templates:
        DB_PASSWD:
          text: '{{ get .Secrets "DB_PASSWD" }}'
        MYSQL_PASSWORD:
          text: '{{ get .Secrets "MYSQL_PASSWORD" }}'
        MYSQL_ROOT_PASSWORD:
          text: '{{ get .Secrets "MYSQL_ROOT_PASSWORD" }}'
        ROMM_AUTH_SECRET_KEY:
          text: '{{ get .Secrets "ROMM_AUTH_SECRET_KEY" }}'
        IGDB_CLIENT_ID:
          text: '{{ get .Secrets "IGDB_CLIENT_ID" }}'
        IGDB_CLIENT_SECRET:
          text: '{{ get .Secrets "IGDB_CLIENT_SECRET" }}'
        STEAMGRIDDB_API_KEY:
          text: '{{ get .Secrets "STEAMGRIDDB_API_KEY" }}'
        MOBYGAMES_API_KEY:
          text: '{{ get .Secrets "MOBYGAMES_API_KEY" }}'
        RETROACHIEVEMENTS_API_KEY:
          text: '{{ get .Secrets "RETROACHIEVEMENTS_API_KEY" }}'
