apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ccm-secrets-sync
  namespace: kube-system
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: proxmox-credentials
  refreshAfter: 1m
  destination:
    name: ccm-proxmox-credentials
    create: true
    type: Opaque
    transformation:
      templates:
        config.yaml:
          text: |
            clusters:
              - url: {{ get .Secrets "url" | quote }}
                insecure: {{ get .Secrets "insecure" }}
                token_id: {{ get .Secrets "token_id" | quote }}
                token_secret: {{ get .Secrets "token_secret" | quote }}
                region: {{ get .Secrets "region" | quote }}