apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cert-manager-secrets-sync
  namespace: networking
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: cert-manager-token
  refreshAfter: 1m
  destination:
    name: cert-manager-token
    create: true
    type: Opaque