apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-credentials-sync
  namespace: development
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: n8n-credentials
  refreshAfter: 1m
  destination:
    name: n8n-credentials
    create: true
    type: Opaque
    transformation:
      templates:
        host:
          text: '{{ get .Secrets "host" }}'
        port:
          text: '{{ get .Secrets "port" }}'
        database:
          text: '{{ get .Secrets "database" }}'
        user:
          text: '{{ get .Secrets "username" }}'
        password:
          text: '{{ get .Secrets "password" }}'
        encryption_key:
          text: '{{ get .Secrets "encryption_key" }}'
