apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-runner-secrets-sync
  namespace: development
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: gitlab-runner-token
  refreshAfter: 1m
  destination:
    name: gitlab-runner-token
    create: true
    type: Opaque
    transformation:
      templates:
        runner-token:
          text: '{{ get .Secrets "runnerToken" }}'
        runner-registration-token:
          text: '{{ get .Secrets "runnerToken" }}'