apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-credentials-sync
  namespace: monitoring
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: grafana-credentials
  refreshAfter: 1m
  destination:
    name: grafana-credentials
    create: true
    type: Opaque
    transformation:
      templates:
        admin-user:
          text: '{{ get .Secrets "admin-user" }}'
        admin-password:
          text: '{{ get .Secrets "admin-password" }}'
        postgres-url:
          text: '{{ get .Secrets "postgres-url" }}'
        POSTGRES_URL:
          text: '{{ get .Secrets "postgres-url" }}'
        GF_DATABASE_URL:
          text: '{{ get .Secrets "postgres-url" }}'