apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hashicorp-vault-secrets-sync
  namespace: secrets
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: vault-postgres-storage
  refreshAfter: 1m
  destination:
    name: vault-postgres-storage
    create: true
    type: Opaque